// Modules to control application life and create native browser window
const { app, BrowserWindow, ipcMain, dialog } = require("electron");
const path = require("path");

let mainWindow;
let youtubeSelectorWindow;
let secondaryWindow = null;

// Creates the main window
function createWindow() {
    const mainWindow = new BrowserWindow({
        width: 1920,
        height: 1080,
        minHeight: 480,
        minWidth: 480,
        titleBarStyle: "hidden",
        titleBarOverlay: {
            color: "#252526",
            symbolColor: "#ffffff",
            height: 30,
        },
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            enableRemoteModule: true,
        },
        autoHideMenuBar: true,
        icon: path.join(__dirname, "VideoPlayerIcon.ico"),
    });

    mainWindow.loadFile("html/index.html");

    mainWindow.on("closed", function () {
        app.quit();
    });

    return mainWindow;
}

// Creates the main window when ready (I believe this was auto-generated by electron for MacOS systems)
app.whenReady().then(() => {
    mainWindow = createWindow();

    app.on("activate", function () {
        if (BrowserWindow.getAllWindows().length === 0)
            mainWindow = createWindow();
    });
});

// Quits the app when all windows are closed (auto-generated by electron)
app.on("window-all-closed", function () {
    if (process.platform !== "darwin") app.quit();
});

// Show open file dialog, only allowing supported video files
ipcMain.handle("showDialog", (e, supportedExtensions) => {
    return dialog.showOpenDialog({
        properties: ["openFile"],
        filters: [
            { name: "Supported Video Files", extensions: supportedExtensions },
        ],
    });
});

// Gets CLI arguments (for whenever a video is Opened With the app)
ipcMain.handle("getVideoArgs", (e) => {
    return process.argv;
});

// Sets the main video player to full screen
ipcMain.handle("setFullscreen", (e, isFullscreen) => {
    mainWindow.setFullScreen(isFullscreen);
});

// Allows the YouTube video selector to communicate with thte main windoww to change the video
ipcMain.handle("changeVideoYoutube", (e, videoPath, videoTitle) => {
    mainWindow.webContents.send('youtube-video-path', `${videoPath}*${videoTitle}`);
    youtubeSelectorWindow.destroy();
});

// Gets the directory of where the app is saved
ipcMain.handle("getAppDirectory", () => {
    if (process.env.NODE_ENV == "Development") {
        return null;
    }

    return app.getAppPath();
});

// Gets the path of the AppData directory
ipcMain.handle("getAppDataDirectory", () => {
    return app.getPath('userData');
});

// Closes the secondary (help) window
ipcMain.handle("closeSecondaryWindow", () => {
    if (secondaryWindow != null) {
        secondaryWindow.destroy();
    }
});

// Opens up the help modal
ipcMain.handle("showHelpModal", (e) => {
    const helpWindow = new BrowserWindow({
        width: 1024,
        height: 768,
        minHeight: 480,
        minWidth: 480,
        titleBarStyle: "hidden",
        resizable: false,
        transparent: true,
        frame: false,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            enableRemoteModule: true,
        },
        type: "toolbar",
        autoHideMenuBar: true,
        icon: path.join(__dirname, "VideoPlayerIcon.ico"),
    });

    helpWindow.loadFile("html/help.html");

    helpWindow.on("blur", () => {
        helpWindow.destroy();
    });

    secondaryWindow = helpWindow;
});

// Opens up the YouTube video selector modal
ipcMain.handle("showYoutubeModal", (e) => {
    youtubeSelectorWindow = new BrowserWindow({
        width: 600,
        height: 250,
        minHeight: 200,
        minWidth: 480,
        titleBarStyle: "hidden",
        resizable: false,
        transparent: true,
        frame: false,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            enableRemoteModule: true,
        },
        type: "toolbar",
        autoHideMenuBar: true,
        icon: path.join(__dirname, "VideoPlayerIcon.ico"),
    });

    youtubeSelectorWindow.loadFile("html/youtube.html");

    youtubeSelectorWindow.on("blur", () => {
        youtubeSelectorWindow.destroy();
    });

    secondaryWindow = youtubeSelectorWindow;
});
